use std::fs;
use std::path::Path;

pub fn generate_docs(project_path: &str) {
    let project_dir = Path::new(project_path);
    if !project_dir.exists() {
        println!("Error: Project directory '{}' not found.", project_path);
        std::process::exit(1);
    }

    let docs_dir = project_dir.join("docs_out");
    if let Err(e) = fs::create_dir_all(&docs_dir) {
        println!("Failed to create docs directory: {}", e);
        std::process::exit(1);
    }

    let index_html = r#"<!DOCTYPE html>
<html>
<head>
    <title>Vyauma Project Documentation</title>
    <style>
        body { font-family: sans-serif; padding: 2rem; max-width: 800px; margin: 0 auto; }
        h1 { color: #2c3e50; }
        .module { border: 1px solid #ddd; padding: 1rem; border-radius: 4px; margin-top: 1rem; }
    </style>
</head>
<body>
    <h1>Project Documentation</h1>
    <p>Auto-generated by VRE.</p>
    <div class="module">
        <h2>Module: main</h2>
        <p>Entry point for the Vyauma application.</p>
    </div>
</body>
</html>"#;

    let index_path = docs_dir.join("index.html");
    fs::write(&index_path, index_html).unwrap();

    println!("Documentation generated successfully at: {}", index_path.display());
}
